### PR TITLE
Line breaks

### PR DESCRIPTION
**Pull request by eirrgang**
Conservatively add a bunch of line breaks to try to reduce diff noise and merge conflicts in future changes.

Hopefully, I didn't break any Jekyll directives.

I figured it would be slightly easier to handle addition of line breaks in future changes than to expect people to diligently remove them, but at least most of the paragraphs are broken into more lines to try to isolate single-word edits a bit more.

If it makes more sense to break lines at 80 characters, I can do that. If we want to break at stricter boundaries, like sentences and fragments, it probably isn't worth the effort of doing that in a single change, but rather something we should just start expecting to see accompanying other changes.

### CODE REVIEW

**Comment by eirrgang** [comment]
Not sure if it is useful to add line breaks arbitrarily (automatically) if we are only going to double them. Maybe it would be better to just add line breaks as part of the proof-reading commits?

**Comment by radifar** [comment]
I think this could generate another issue, for example if we were to open this website on android or iphone (which use various window size) it won't looks nice. Nowadays we have to keep [responsive web design](https://web.dev/responsive-web-design-basics/) in mind.

**Comment by janash** [comment]
> 
> 
> I think this could generate another issue, for example if we were to open this website on android or iphone (which use various window size) it won't looks nice. Nowadays we have to keep [responsive web design](https://web.dev/responsive-web-design-basics/) in mind.

Thanks @radifar! I really appreciate your comments on these issues and your participation with MolSSI. 

In this case, we're trying to reduce probability that we would encounter git conflicts by putting sentences on their own lines. We need to check if this will work with the template, but it should work with general markdown. I think we have decided to abandon this PR, which was created by running an autoformatter, in favor of manual adding these linebreaks while proofreading.

We're trying to get another release version out of the workshop by the end of July. @eirrgang , @sjayellis and I are working in a group. Would you like to help / attend our next meeting? You can send me an email if you're interested (janash@vt.edu).

**Comment by radifar** [comment]
Ah I see, I didn't really pay attention to that diff noise and git conflicts. I just tried to check this PR locally and compare with the gh-pages branch (preview them using Jekyll) and find them identical except for the png vs svg images. I just remembered that in Markdown a single new line is ignored, my bad. Oh btw, I found no directive getting broken (so far). So maybe it is OK to use autoformatting at first and then manually adding them in the next editing/PR. Overall I'm OK with the idea of adding new line to reduce diff noises and git conflicts.

And thank you for your offer, I'll email you later 😄 .

**Comment by eirrgang** [comment]
After discussion, a better strategy is probably just to agree to make sensible line breaks at natural points in sentences and phrases localized to the sentence(s) around actual content changes. Divergent edits will likely require manual merge conflict resolution, and we will have to be diligent not to regress other edits. But we have that problem already, and the issue should become increasingly simpler as more line breaks are introduced.

**Pull request closed without merging**
